name: Discord Notification

on:
  push:
    branches:
      - main

jobs:
  notify:
    uses: TasksGoalsApp/.github/.github/workflows/discord-notification.yml@main
    secrets:
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
